namespace: ecommerce-ns

replicas: 5

image:
  repository: sukhesh77/ecommerce-app
  tag: v1.0.0
  port: 80

service:
  name: ecommerce-service
  type: LoadBalancer
  port: 80

labels:
  app: ecommerce

container:
  name: ecommerce-container
