apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://sukhesh77.github.io/E-commerce-app
    chart: ecommerce-app
    targetRevision: "*"
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true